@Marketplace_HostAddress = http://localhost:5190

### --- ORDERS ---

### Get All Orders
GET {{Marketplace_HostAddress}}/api/orders

### Get Order by ID
@orderId = 1
GET {{Marketplace_HostAddress}}/api/orders/{{orderId}}

### Create Sample Order
POST {{Marketplace_HostAddress}}/api/orders
Content-Type: application/json

{
  "platform": "Trendyol",
  "date": "2026-03-03T10:00:00Z",
  "items": [
    {
      "name": "Laptop",
      "purchasePrice": 10000,
      "salePrice": 15000,
      "commissionRate": 10,
      "shippingCost": 100,
      "quantity": 2
    },
    {
      "name": "Mouse",
      "purchasePrice": 200,
      "salePrice": 150,
      "commissionRate": 5,
      "shippingCost": 20,
      "quantity": 5
    }
  ]
}

### Update Order
PUT {{Marketplace_HostAddress}}/api/orders/{{orderId}}
Content-Type: application/json

{
  "platform": "Trendyol",
  "date": "2026-03-03T10:00:00Z",
  "items": [
    {
      "name": "Laptop Edited",
      "purchasePrice": 10000,
      "salePrice": 15500,
      "commissionRate": 10,
      "shippingCost": 100,
      "quantity": 2
    }
  ]
}

### Delete Order
DELETE {{Marketplace_HostAddress}}/api/orders/{{orderId}}


### --- PLATFORMS ---

### Get All Platforms
GET {{Marketplace_HostAddress}}/api/platforms

### Get Platform by ID
@platformId = 1
GET {{Marketplace_HostAddress}}/api/platforms/{{platformId}}

### Create Sample Platform
POST {{Marketplace_HostAddress}}/api/platforms
Content-Type: application/json

{
    "name": "Trendyol"
}

### Update Platform
PUT {{Marketplace_HostAddress}}/api/platforms/{{platformId}}
Content-Type: application/json

{
    "name": "Trendyol Edited"
}

### Delete Platform
DELETE {{Marketplace_HostAddress}}/api/platforms/{{platformId}}


### --- REPORTS ---

### Get Summary Report
GET {{Marketplace_HostAddress}}/api/report/summary

### Get Platform Report
GET {{Marketplace_HostAddress}}/api/report/platform

### Get Loss Report
GET {{Marketplace_HostAddress}}/api/report/loss

### Get Anomaly Report
GET {{Marketplace_HostAddress}}/api/report/anomaly

### Get Trend Report
GET {{Marketplace_HostAddress}}/api/report/trend

### Get Risk Report
GET {{Marketplace_HostAddress}}/api/report/risk
